# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96393a9e3326a109513118e31e082c6e2e2c67c17afd88ee8384c6784a58526bd3419ebc143a0e4071271d20b10615a69a96de94cd84f68a41c05b52a50d36a5

test:
  secret_key_base: 742844042a0b509d68cebb2c92cfe567ba3280ad4810c2dd94b809fc8b68c7b11cc450ea22790e89a5c6b12cf87f4fbc22f940cf8ec33e6ca8c33ca75c5ae1a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
